# Generated by Django 4.1.5 on 2023-08-21 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WalletWise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundschange',
            name='destination',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='associatedFundsChanges', to='WalletWise.funds'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fundschange',
            name='reoccuring',
            field=models.BooleanField(default=False),
        ),
    ]
