# Generated by Django 4.1.5 on 2023-10-14 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WalletWise', '0003_alter_funds_amount_alter_fundschange_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundschange',
            name='description',
            field=models.CharField(default='No Description', max_length=200),
        ),
    ]
